# Generated by Django 4.1.4 on 2023-01-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Autor')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido del Autor')),
                ('facebook', models.URLField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, max_length=100, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('web', models.URLField(blank=True, max_length=100, null=True, verbose_name='Web')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('status', models.BooleanField(default=True, verbose_name='Autor Activo / Autor No Activo')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('status', models.BooleanField(default=True, verbose_name='Categoría Activa / Categoría No Activa')),
                ('content', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
