# Generated by Django 4.1.4 on 2023-01-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_alter_autor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
