# Generated by Django 4.1.4 on 2023-01-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0010_alter_post_autor_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
