# Generated by Django 4.1.4 on 2023-01-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0011_remove_post_autor_remove_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen'),
        ),
    ]
