# Generated by Django 4.1.4 on 2023-01-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0012_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
    ]
