# Generated by Django 4.1.4 on 2023-01-03 06:10

import AppBlog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0013_alter_autor_published_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default='', max_length=100, verbose_name=AppBlog.models.Autor),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppBlog.category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
