# Generated by Django 4.1.4 on 2023-01-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0014_post_autor_post_category_post_slug_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='AppBlog.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='Slug'),
        ),
    ]
