# Generated by Django 4.1.4 on 2023-01-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0016_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo / No Activo'),
        ),
    ]
