# Generated by Django 4.1.4 on 2023-01-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0017_alter_about_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(verbose_name='Imagen'),
        ),
    ]
